### ISSUE TITLE
Error on Connect: Command "extension.connect" not found 

### ISSUE THREAD

**Issue by brase** [Microsoft/vscode-mssql#1022]
- MSSQL Extension Version:  1.2.1
- VSCode Version: 1.18.0
- OS Version: Windows 10 1710

Steps to Reproduce:

1. Open SQL-File
2. Execute Connect

![76868346-492a-4b1d-828f-4d2f8786a16c](https://user-images.githubusercontent.com/170088/32606434-9a74376a-c555-11e7-88db-3943b03f0121.gif)

**Comment by kburtram** [comment]
@brase have you tried to uninstall and reinstall mssql extension?

@MattIrv could you please investigate what's happening here?

**Comment by brase** [comment]
Uninstall -> Reload -> Install -> Reload fixed it.

Thank you!

**Comment by MattIrv** [comment]
I'm glad to hear it's working now.

Other users have reported this bug in the past, and suggested it might have something to do with conflicts between other extensions (see https://github.com/Microsoft/vscode-mssql/issues/383) but we've never been able to get a consistent repro for it.

Is there any chance you'd be willing to share a list of your installed extensions so that we can get another data point on this? You should be able to get the list by running `code --list-extensions` from the Windows command prompt or Powershell.

**Comment by spdjudd** [comment]
I just had this issue, fixed in the same way with a reinstall of the extension.  Pretty sure it was working when I originally installed it, then after several Code and extension updates it wasn't working today.

Here are the extensions I have installed:
DotJoshJohnson.xml
eriklynd.json-tools
filipw.scriptcsRunner
mohsen1.prettify-json
ms-mssql.mssql
ms-python.python
ms-toolsai.vscode-ai
ms-vscode.azure-account
ms-vscode.csharp
ms-vscode.PowerShell
PeterJausovec.vscode-docker
PKief.material-icon-theme

**Comment by brase** [comment]
Sorry, I am a bit late. Here are my installed extensions

```
2gua.rainbow-brackets
adamvoss.yaml
ban.spellright
codezombiech.gitignore
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
donjayamanne.githistory
DotJoshJohnson.xml
DougFinke.vscode-pandoc
dracula-theme.theme-dracula
EditorConfig.EditorConfig
Equinusocio.vsc-material-theme
espresso3389.genuuid
formulahendry.auto-close-tag
groksrc.ruby
HookyQR.beautify
hoovercj.haskell-linter
Ionide.Ionide-FAKE
Ionide.Ionide-fsharp
Ionide.Ionide-Paket
jcanero.hoogle-vscode
johnpapa.winteriscoming
justusadam.language-haskell
ms-mssql.mssql
ms-vscode.azure-account
ms-vscode.cpptools
ms-vscode.csharp
ms-vscode.PowerShell
msjsdiag.debugger-for-chrome
PeterJausovec.vscode-docker
PKief.material-icon-theme
pprice.better-merge
robinbentley.sass-indented
shardulm94.trailing-spaces
Vans.haskero
vsciot-vscode.vscode-arduino
vscodevim.vim
waderyan.gitblame
```

**Comment by KuromiAK** [comment]
I encountered this problem and found this error in dev tools:
``[Extension Host] Activating extension `ms-mssql.mssql` failed:  Cannot find module 'vscode-nls'``
Running `npm install` in the extension folder (C:\Users\USERNAME\.vscode\extensions\ms-mssql.mssql-1.2.1) fixed it for me.

**Comment by grothem** [comment]
I've got this same issue. I've tried unistalling/reinstalling and disabling all of my other extensions, but I'm still getting the error.

**Comment by grothem** [comment]
I ended up solving this problem by going into `%USERPROFILE%\.vscode\extensions` and deleting the ms-mssql folder and reinstalling. I tried uninstalling and reinstalling, but after uninstalling, I would go into the extensions folder and it would still be there.

**Comment by MrDatuPuti** [comment]
Agreed, 64 bit is broken, had to reinstall 32 bit version in able to connect to database.

**Comment by ihavenonickname** [comment]
@grothem 

Saved my day. Thank you!!!

**Comment by SeaDude** [comment]
For those on linux, deleting the `mssql` folder from `/home/.vscode` then reinstalling the extension worked for me.

**Comment by Zakaria-pro** [comment]
1. CTRL + SHIFT + P 
2. Reload window
3. Wait 
the extension worked for me.

**Comment by ravi-achar** [comment]
I am seeing this issue on my VS code instance from past 10 days. I have tried everything suggested in this thread but have not been able to get it to work. I am running VS Code on a Windows 10 VM.

**Comment by les-portugal** [comment]
I discovered this issue when it started happening maybe a month ago.
My VSCode version is 1.78.0, running on Windows 10.
I was able to resolve this by first uninstalling all the SQL Server related extensions that I had installed.
I then uninstalled SQL Server (mssql) extension, closed VSCode - ensured the %USERPROFILE% folder was clean.
I then re-opened VSCode, and re-installed the mssql extension.

Got this in the OUTPUT tab:
```
Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: win32, x86_64 (Windows)

Installing SQL tools service to c:\Users\lportugal\.vscode\extensions\ms-mssql.mssql-1.18.0\sqltoolsservice\4.5.1.6\Windows.
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/4.5.1.6/microsoft.sqltools.servicelayer-win-x64-net7.0.zip
(69974 KB) .................... Done!
Installing ...
Done! 848 files unpacked.
```
It all works now!
