### ISSUE TITLE
MicrosoftSqlToolsServiceLayer.exe consuming a lot of memory after vs code update

### ISSUE THREAD

**Issue by Eigh** [microsoft/vscode-mssql#1028]
- MSSQL Extension Version: 1.2.1
- VSCode Version: 1.18.0
- OS Version: Windows 7 Professional (64-bit)

Steps to Reproduce:

1. Opening/Editing sql files. It might take a while before memory shoots up.
![2017-11-15_10-23-28](https://user-images.githubusercontent.com/5112226/32861616-11d84a2c-ca0a-11e7-864f-721a86ac347a.png)
![capture](https://user-images.githubusercontent.com/5112226/32861623-16ff8678-ca0a-11e7-8f03-0d905bcaeb1d.PNG)

**Comment by MattIrv** [comment]
Thanks for the report. I haven't seen this before or been able to reproduce it, so if you have any additional information about what steps might cause it to happen please let me know.

Is restarting VS Code a suitable workaround or does this happen every time you try to use the extension?

**Comment by sidewinder94** [comment]
I'm having the same issue here. 
The helper process RAM usage grows until none is left (in my case it grows up to 12Go).

MSSQL Extenstion Ver. : 1.3.0
VS Code Ver. : 1.21.1
OS Version : Windows 10

Killing the helper process and restarting Code makes it work again until the next occurrence of the problem. Happens multiple times a day.

**Comment by MattIrv** [comment]
Unfortunately we still haven't been able to reproduce this bug. @sidewinder94 does this seem to happen when you're connected to a certain server or have certain files open? If it happens when connected to a server, do you know what version of SQL Server it is? Thanks!

**Comment by sidewinder94** [comment]
In my case, it happens exclusively when connected to a server.
I don't think, it's related to a certain file.

I think it's SQL Server v12 (I think the "commercial" name is SqlServer 2014).

I'll update this answer tomorrow if I'm mistaken about the SQLServer version.

**Comment by CrossTyreck** [comment]
I have had the same issue. I am on SQL Server v.13.0.4411.0. 

I believe my issue is centered around a certain file though. Here are my observations:

If I load a stored procedure with a lot of SQL (1800+ lines) memory just sits at 19.3 MB. 

When I connect to a db (no execution just connecting) the memory usage starts climbing and bounces back and forth for 20 min till it finally taps out my system resources and I have to disable the extension and reload the project.

If I remove all the lines from the file after connecting to the db the memory still continues to climb.

**Comment by sidewinder94** [comment]
I can now say for certain that the issue happens 100% of the time with one certain file, not even a huge one (~340 lines for 19Ko).

There are some SQLCMD variable declarations and usage though, not sure if it can narrow the problem down.

What's more ? The issue happens in SSMS too (2014 and 2017) not sure if the two projects are sharing components, but I might have to open a bug over there too.

Any way to profile that on my computer ? The file which I use to reproduce is owned by my employer, and I'm pretty sure I'm not allowed to send it or even part of it.

**Comment by guillemsola** [comment]
I came here surprised by the huge amount of RAM this extension was consuming.

![image](https://user-images.githubusercontent.com/610476/52116625-e5032980-2611-11e9-861b-ece9c400135d.png)

I was working with a big db project and has opened some tabs with at least a couple of >1000 lines stored procedures

**Comment by Chris2011** [comment]
Today I had the same, but I didn't do anything with VS Code today. The thing is, it ran for round about 6h after I woke up my laptop. It runs more or less in the background. I'm using another IDE today, this is, why I said, I didn't do anything with VS Code today, only opening it. The layer ate 8GB ram, after I killed it, I got the message from VS Code: 

![image](https://user-images.githubusercontent.com/795658/54538717-07b88a00-4995-11e9-9990-b1362343a93f.png)

So if I can help with more information, let me know.
Windows 10 1809 (64bit), newest VS Code 1.32.2.

**Comment by oappelt** [comment]
I just had to kill MicrosoftSqlToolsServiceLayer process occupying 20 GB of RAM (not virtual -that's at 30 GB).
ADS had been running for days - but I just closed all instances and above process is still sitting on all that RAM - in fact it seems like it was still grabbing more RAM  - it went from 20.4 to 20.6 GB within a few minutes (with no instance of ADS running).

ADS 1.10
On Ubuntu Linux 16.04.

**Comment by Eigh** [comment]
Hi @MattIrv,

Apologies, I submitted this issue almost 2 years ago and was not able to follow up and provide more details. But it seems this has been resolved already? I don't encounter the issue anymore. I am not sure about the others though. Should we close this one?

**Comment by kburtram** [comment]
@Eigh thanks for the update.  I noticed a couple weeks ago SQL Tools Service get into a state where it would consume memory unbounded.  It went to about ~15GB before I killed it.  I think the problem is when the query execution code gets in a bad state for some reason.

**Comment by Eigh** [comment]
Hi @kburtram ,

Ohhh, thanks for the info! Then I will do some more testing and see if there is an unusual memory consumption happening again. We can keep this ticket open I guess to see if we can extract more data on what's causing the spike in memory consumption.

**Comment by kaschuba** [comment]
This is still happening. I am connected to a server and the search fails. I get a slew of error messages and then the RAM consumes all physical RAM (in my case 30GB of 32GB) and leaves my PC slow.

**Comment by kaschuba** [comment]
![Image](https://github.com/user-attachments/assets/199d2568-01c9-4fcd-9045-2fa0a4b7a4f1)
To get into this state I was running a query, I walked away as it was taking a bit of time and the query was still running when I came back but I can no longer stop the query. The option has disappeared but its still requesting me to do so.

![Image](https://github.com/user-attachments/assets/6c75476a-bf4e-4900-9441-a1b1f076486d)

**Comment by BandHDataAnalyst** [comment]
![Image](https://github.com/user-attachments/assets/91cdaa54-ff81-4f8d-9c2c-67baaf978fc4)

I have uninstalled and reinstalled VScode, and this same issue is persisting. It's caused my work laptop to crash four teams in as many business days. I have 16GB of RAM on my machine and when VSCode is open, I'm constantly running at 14.5 - 15 GB of RAM usage, and that's just being connected to my Azure Server, not even running a query. 

All my extensions are up to date. Please advise as this is becoming a significant blocker.

**Comment by kburtram** [comment]
> Also appears my queries are getting stuck in a stale state when this runaway RAM grabbing is occurring. The Stop Executing Query button has also disappeared from my VSCode UI.

hi @BandHDataAnalyst, if you're experiencing a problem with query execution and memory consumption, could you please log a new issue with repro steps for the current build?  This issue is already closed so it's not being tracked for further investigation.  Thanks!
